server:
  port: 12301

napcat:
  start: 'G:\01mr\workspace\01work\0000\long-song-reborn\05qq\NapCat.Shell\NapCatWinBootMain.exe 3527047850'
  stop: 'taskkill -f -im QQ.exe'

onebot:
  server: http://127.0.0.1:12300

meme:
  start: 'meme run'
  stop: 'taskkill -f -im meme.exe'
  server: http://127.0.0.1:2233/memes

sqlite:
  path: 'G:\01mr\workspace\01work\0000\long-song-reborn\06database'

material:
  web-path: http://127.0.0.1:12301
  local-path: 'G:\01mr\workspace\01work\0000\long-song-reborn\02material'
  temp-path: 'G:\01mr\workspace\01work\0000\long-song-reborn\04temp'