server:
  port: 12301

onebot:
  server: http://192.168.1.132:12300

meme:
  server: http://127.0.0.1:2233/memes

material:
  web-path: http://192.168.1.140:12301
  local-path: 'G:\01mr\workspace\01work\0000\long-song-reborn\02material'
  temp-path: 'G:\01mr\workspace\01work\0000\long-song-reborn\04temp'